CREATE TABLE HOTEL (
HOTELID VARCHAR (10) NOT NULL, 
CITY CHAR (10) NOT NULL,
STATUE CHAR (10) NOT NULL, 
PHONENO CHAR (11) NOT NULL, 
ADDRESS VARCHAR (20) NOT NULL, 
PRIMARY KEY (HOTELID) ,
);


CREATE TABLE CUSTOMER (
CUSTOMERID CHAR (10) NOT NULL, 
CNAME VARCHAR (10) NOT NULL, 
PHONENO CHAR (11) NOT NULL, 
CITY CHAR (10) NOT NULL, 
STATUE CHAR (10) NOT NULL, 
PRIMARY KEY (CUSTOMERID) ,
);

CREATE TABLE ROOMS (
ROOMNO CHAR (10), 
ROOMTYPE VARCHAR (10) NOT NULL, 
HOTELID VARCHAR (10) NOT NULL,
CUSTOMERID CHAR (10) NOT NULL,
PRIMARY KEY (ROOMNO), 
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER , 
FOREIGN KEY (HOTELID) REFERENCES HOTEL,
);


CREATE TABLE RESERVATION (
RESERVATIONNO CHAR (10) NOT NULL, 
CUSTOMERID CHAR (10) NOT NULL, 
CHECKINDATE DATE NOT NULL, 
CHECKOUTDATE DATE NOT NULL, 
FNAME VARCHAR (7) NOT NULL, 
CNAME VARCHAR (7) NOT NULL,  
NOOFGUEST CHAR (10) NOT NULL, 
RESERVATIONDATE CHAR (10) NOT NULL, 
PRIMARY KEY (RESERVATIONNO), 
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER ON DELETE CASCADE ON UPDATE CASCADE ,
);

CREATE TABLE BILLING (
BILLINGNO CHAR (10), 
CREDITCARDNO VARCHAR (16) NOT NULL, 
PAYMENTDATE DATE NOT NULL, 
RESERVATIONNO CHAR (10) NOT NULL, 
PRIMARY KEY (BILLINGNO), 
FOREIGN KEY (RESERVATIONNO) REFERENCES RESERVATION,
);

CREATE TABLE ROOMRESERVATION (
ROOMNO CHAR(10) NOT NULL,
RESERVATIONNO CHAR(10) NOT NULL,
PRIMARY KEY (ROOMNO, RESERVATIONNO), 
FOREIGN KEY (ROOMNO) REFERENCES ROOMS (ROOMNO), 
FOREIGN KEY (RESERVATIONNO) REFERENCES RESERVATION (RESERVATIONNO)
);
